spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/event_manager
    username: root
    password: rootroot
  data:
    redis:
      host: localhost
      port: 6379
  #设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #设置用邮件发送相关
  mail:
    host: smtp.163.com
    port: 465
    username: event_manager@163.com
    password: YXfdF75mRMRDTTMy
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


#Java驼峰命名与Mysql的下划线命名之间的转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#将上传的图片存储到本地文件夹下，用于静态资源映射
file:
  upload-path: D:/tmp_project/vue_learn/image_store_for_eventManager/

frontend:
  url: localhost


